#!/usr/bin/env php
<?php

if ( php_sapi_name() !== 'cli' ) {
	echo "This script only works in CLI mode\n";
	exit( 1 );
}

if ( count( $argv ) < 3 ) {
	echo "Usage: make-wmf-branch <new-version> <old-version> <path to clone>\n";
	echo "Example: make-wmf-branch 1.20wmf2 1.20wmf1\n";
	echo " <path to clone>, if given, is a local clone on disk to use\n";
	exit( 1 );
}

$newVersion = $argv[1];
$oldVersion = $argv[2];
$clonePath = isset( $argv[3] ) ? $argv[3] : null;

require_once( __DIR__ . '/MakeWmfBranch.php' );

$obj = new MakeWmfBranch( $newVersion, $oldVersion );
$obj->execute( $clonePath );
