((prog-mode
  . ((mode . flycheck)
	 (tab-width . 4)
  	 (indent-tabs-mode . t)
	 (c-basic-offset . 4)
	 (c-offsets-alist . ((annotation-var-cont . +)
						 (arglist-intro . + )
						 (brace-list-intro . +)
						 (cpp-define-intro c-lineup-cpp-define +)
						 (cpp-macro-cont . +)
						 (defun-block-intro . +)
						 (func-decl-cont . +)
						 (inclass . +)
						 (incomposition . +)
						 (inexpr-class . +)
						 (inexpr-statement . +)
						 (inextern-lang . +)
						 (inher-intro . +)
						 (inmodule . +)
						 (innamespace . +)
						 (knr-argdecl-intro . +)
						 (lambda-intro-cont . +)
						 (member-init-intro . +)
						 (statement-block-intro . +)
						 (statement-case-intro . +)
						 (substatement . +)
						 (template-args-cont c-lineup-template-args +)
						 (substatement-label . 2)
						 (annotation-top-cont . 0)
						 (block-close . 0)
						 (block-open . 0)
						 (brace-entry-open . 0)
						 (brace-list-close . 0)
						 (brace-list-entry . 0)
						 (brace-list-open . 0)
						 (case-label . 0)
						 (catch-clause . 0)
						 (class-close . 0)
						 (comment-intro . 0)
						 (composition-close . 0)
						 (composition-open . 0)
						 (defun-close . 0)
						 (defun-open . 0)
						 (do-while-closure . 0)
						 (else-clause . 0)
						 (extern-lang-close . 0)
						 (extern-lang-open . 0)
						 (friend . 0)
						 (inline-close . 0)
						 (knr-argdecl . 0)
						 (module-close . 0)
						 (module-open . 0)
						 (namespace-close . 0)
						 (namespace-open . 0)
						 (statement . 0)
						 (statement-case-open . 0)
						 (topmost-intro . 0)
						 (access-label . -)
						 (stream-op . c-lineup-streamop)
						 (arglist-cont-nonempty first
												php-lineup-cascaded-calls
												c-lineup-arglist)
						 (inher-cont . c-lineup-multi-inher)
						 (member-init-cont . c-lineup-multi-inher)
						 (c . c-lineup-C-comments)
						 (string . c-lineup-dont-change)
						 (arglist-close . php-lineup-arglist-close)
						 (statement-cont first php-lineup-cascaded-calls
										 php-lineup-string-cont +)))
	 (c-hanging-braces-alist
	  (defun-open after)
	  (block-open after)
	  (defun-close))
	 (lice:default-license . "gpl-3.0")))
	 (eval
	  . (progn (when (fboundp 'delete-trailing-whitespace)
	    		 (delete-trailing-whitespace))
	    	   (when indent-tabs-mode
	    		 (tabify (point-min) (point-max)))
	    	   (when (fboundp 'subword-mode)
	    		 (subword-mode)))))

