#!/usr/bin/env php
<?php

/*
 * Copyright (C) 2019  Wikimedia Foundation
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @author Mark A. Hershberger <mah@nichework.com>
 */

namespace Wikimedia\Release;

require __DIR__ . '/vendor/autoload.php';

use splitbrain\phpcli\PSR3CLI;
use splitbrain\phpcli\Options;
use Wikimedia\Release\Branch;

class MakeBranch extends PSR3CLI {

	protected function setup( Options $opt ) {
		$this->setAutocatch();
		Branch::setupOptions( $opt );
	}

	protected function main( Options $opt ) {
		$branch = Branch::getBrancher( $opt->getCmd(), $opt, $this );
		$branch->initialize();
		$branch->execute();
	}
}

$cli = new MakeBranch();
$cli->run();
