#!/bin/bash

set -eu -o pipefail

function usage {
    cat <<EOF
Usage: $0 base-image
EOF
    exit 1
}

if [ $# -ne 1 ]; then
    usage
fi

base="$1"

tag=$(echo "$base" | cut -d: -f2)
if [ -z "$tag" ]; then
    echo "Could not extract the tag from base image name: $base"
    exit 1
fi

output_image="docker-registry.discovery.wmnet/restricted/mediawiki-multiversion-debug:$tag"

cat <<EOF | docker build -t "$output_image" -f- empty/
FROM $base
USER root
RUN apt-get update && apt-get install php-tideways-xhprof
USER www-data
EOF

echo "$output_image" > last-debug-build.tmp
mv last-debug-build.tmp last-debug-build

