#!/bin/bash

set -eu -o pipefail

function usage {
    cat <<EOF
Usage: $0 base-image
EOF
    exit 1
}

if [ $# -ne 1 ]; then
    usage
fi

base="$1"

tag=$(support/extract-image-tag "$base")
if [ -z "$tag" ]; then
    echo "Could not extract the tag from base image name: $base"
    exit 1
fi

output_image="docker-registry.discovery.wmnet/restricted/mediawiki-multiversion-debug:$tag"

echo "** Building debug image: $output_image **"

cat <<EOF | docker build \
                   --build-arg "http_proxy=${http_proxy:-}" \
                   --build-arg "https_proxy=${https_proxy:-}" \
                   -t "$output_image" -f- empty/
FROM $base
USER root
RUN apt-get update && apt-get install php-tideways-xhprof
USER 33
EOF

echo "$output_image" > last-debug-build.tmp
mv last-debug-build.tmp last-debug-build

