#!/usr/bin/env bash

set -eu -o pipefail

function usage {
    cat <<EOF
Usage: $0 workdir-volume-name

Creates a docker volume by the specified name.
Changes ownership of the volume to www-data.

EOF
    exit 1
}

function setup_workdir {
    local workdir="$1"

    if [ "$(docker volume ls -q -f "name=$workdir" | wc -l)" -eq 0 ]; then
	echo "Creating volume $workdir"
	docker volume create "$workdir"
    fi

    # shellcheck disable=SC2016
    docker run --rm \
	   -v "$workdir:/workdir" \
	   docker-registry.wikimedia.org/wikimedia-buster \
	   bash -c 'if [ $(/bin/ls -ld /workdir | cut -d" " -f3) != www-data ]; then chown -R www-data: /workdir; fi'
}

if [ "$#" -ne 1 ]; then
    usage
fi

workdir="$1"

setup_workdir "$workdir"
