#!/usr/bin/env bash

set -eu -o pipefail

if [ ! -f last-build ]; then
    echo Nothing to push yet
    exit 1
fi

image=$(cat last-build)
image_base=$(echo "$image" | sed -r -e 's/^(.*):[^:]+$/\1/')
image_latest="$image_base:latest"

docker tag "$image" "$image_latest"

for image in "$image" "$image_latest"; do
    echo "Pushing $image"
    time sudo /usr/local/bin/docker-pusher "$image"
done
