#!/bin/bash

set -eu -o pipefail

MEDIAWIKI_RELEASES_VALUES_FILE=/etc/helmfile-defaults/mediawiki/release/mwdebug-pinkunicorn.yaml

function same {
    diff "$1" "$2" >/dev/null
}

cd "$(dirname "$MEDIAWIKI_RELEASES_VALUES_FILE")"

# Populate the file by reading from stdin
cat > "$MEDIAWIKI_RELEASES_VALUES_FILE.tmp"
trap 'rm -f $MEDIAWIKI_RELEASES_VALUES_FILE.tmp' EXIT

if [ -f "$MEDIAWIKI_RELEASES_VALUES_FILE" ] && same "$MEDIAWIKI_RELEASES_VALUES_FILE.tmp" "$MEDIAWIKI_RELEASES_VALUES_FILE"; then
    # The file contents didn't change.  Bail
    exit 0
fi

mv "$MEDIAWIKI_RELEASES_VALUES_FILE.tmp" "$MEDIAWIKI_RELEASES_VALUES_FILE"
git add "$MEDIAWIKI_RELEASES_VALUES_FILE"
git commit -m "Updating release"
