#!/usr/bin/env php
<?php

/**
 * Class ExecException
 */
class ExecException extends Exception {}

/**
 * Validation on the command line arguments
 * @param array $argv
 * @return array
 */
function get_args( $argv ) {
	if ( count( $argv ) == 3 ) {
		return array( $argv[1], $argv[2] );
	} else {
		print "usage: $argv[0] oldbranch newbranch\n";
		print "  example: $argv[0] origin/wmf/1.30.0-wmf.1 origin/wmf/1.30.0-wmf.2\n";
		exit(1);
	}
}

/**
 * Wrapper around exec to throw more useful exception when
 * things go sideways
 * @param string $command
 * @throws ExecException
 * @return array
 */
function capture_output( $command ) {
	$cwd = getcwd();
	$output = array();
	exec( $command, $output, $status );
	if( $status != 0 ) {
		throw new ExecException( "Error in command: $command\nDirectory: $cwd\nStatus: $status\nOutput: "
			. print_r( $output) . "\n"
		);
	}
	return $output;
}

/**
 * Get a list of records, one for each submodule.
 *  Each record contains "name", "oldrev", and "newrev"
 * @param string $oldbranch
 * @param string $newbranch
 * @param string $type extensions or skins
 * @return array
 */
function get_submodule_versions( $oldbranch, $newbranch, $type ) {
	$retval = array();
	$extrecord = array();
	foreach ( explode( "\n", git_submodule_diff_output( $oldbranch, $newbranch, $type ) ) as $line ) {
		#diff --git a/extensions/AbuseFilter b/extensions/AbuseFilter
		if( preg_match( "!^diff --git a/$type/([^\. ]+) b/$type/([^\. ]+)!", $line, $matches ) ) {
			if ( $matches[1] === 'README' ) {
				continue;
			}

			if( count( $extrecord ) > 0 ) {
				$retval[] = $extrecord;
				$extrecord = array();
			}
			$extrecord['name'] = $matches[1];
		}
		#-Subproject commit 0c6faec654e25cd5ac8141d4c3f3793c2caeb0e9
		elseif( preg_match( '!^-Subproject commit ([a-f0-9]*)!', $line, $matches ) ){
			$extrecord['oldrev'] = $matches[1];
		}
		#+Subproject commit d693a1bca606473ae9ec8513ad90ddaa80de351d
		elseif( preg_match( '!^\+Subproject commit ([a-f0-9]*)!', $line, $matches ) ) {
			$extrecord['newrev'] = $matches[1];
			$retval[] = $extrecord;
			$extrecord = array();
		}
	}
	return $retval;
}

/**
 * Fetch an array of the change's subject for a given path, along with a bug number.
 * @param string $oldRev
 * @param string $newRev
 * @parma null|string $type
 * @param null|string $name
 * @throws Exception
 * @return array
 */
function useful_git_log( $oldRev, $newRev, $type = null, $name = null ) {
	$gitDir = getcwd();
	if ( $name ) {
		$myDir = $type ? "$gitDir/$type/$name" : "$gitDir/$name";
	} else {
		$myDir = $gitDir;
	}

	if( !is_dir( $myDir ) ) {
		return "";
	}
	chdir( $myDir );
	$retval = full_git_log_as_array( $oldRev, $newRev );
	$gitLog = array();
	foreach( $retval as $commit ) {
		$lines = array_filter( explode( "\n", $commit['message'] ) );
		$first = true;
		$subject = '';
		$bugs = array();
		foreach( $lines as $line ) {
			if( $first ) {
				$first = false;
				if( preg_match( "/\(?(Bug|RT)\s*(T?\d+)\)?\s*(.+)/i", $line, $issueRes ) ) {
					$bugs[] = $issueRes[2];
					$subject = $issueRes[3];
				} else {
					$subject = $line;
				}
			} elseif( preg_match( "/(Bug|RT):\s*(T?\d+)/i", $line, $issueRes ) ) {
				$bugs[] = $issueRes[2];
			}
		}
		// Trim down to the first bit
		$subject = trim( ltrim( trim( $subject ), '-' ) );
		$subject = preg_replace( "/    .+$/i", '', $subject );
		$gitLog[] = array(
			'hash' => substr( $commit['hash'], 1, 8 ),
			'subject' => $subject,
			'bugs' => $bugs,
		);
	}
	chdir( $gitDir );
	return $gitLog;
}

/**
 * @param string $oldRev
 * @param string $newRev
 * @return array
 * @throws Exception
 */
function full_git_log_as_array( $oldRev, $newRev ) {
	$command = "git log --format=medium --cherry-pick --right-only --no-merges $oldRev..$newRev";
	try {
		$output = capture_output( $command );
	} catch( ExecException $e ) {
		throw new Exception( "Problem with command: $command\n"
			. "******** LIKELY CAUSE: you need to run 'git fetch --all' in a sub directory"
		);
	}
	$history = array();
	$commit = array();
	foreach( $output as $line ) {
		if( strpos( $line, 'commit ' ) === 0 ) {
			if( $commit ) {
				array_push( $history, $commit );
				$commit = array();
			}
			$commit['hash']   = substr( $line, strlen( 'commit' ) );
			continue;
		} elseif( strpos( $line, 'Author' ) === 0 || strpos( $line, 'Date' ) === 0 ) {
			continue;
		} else {
			if( isset( $commit['message'] ) ) {
				$commit['message'] .= "\n" . $line;
			} else {
				$commit['message'] = $line;
			}
			continue;
		}
	}

	// push the last commit from the diff to the $history array
	if( $commit )
		array_push( $history, $commit );

	return $history;
}

/**
 * git command for getting the diff list for extensions.
 * @param string $oldbranch
 * @param string $newbranch
 * @param string $type
 * @return string
 */
function git_submodule_diff_output( $oldbranch, $newbranch, $type ) {
	return shell_exec( "git diff --submodule=short $oldbranch $newbranch $type" );
}

/**
 * filter_git_output - perform any extra functions needed prior to posting to
 *  a wiki page (sanitization, making obvious removals, linking bugs, etc)
 * @param array $logoutput
 * @return string
 */
function filter_git_output( $logoutput ) {
	$retval = '';
	if ( !$logoutput ) {
		return $retval;
	}

	$skipLines = array(
		'Localisation updates from',
		'COMMITMSG', // Fix for escaping fail leaving a commit summary of $COMMITMSG
		'Add (\.gitreview( and )?)?\.gitignore',
		'Creating new WMF', // Branching commit; set version, defaultbranch, add submodules
		'Updating development dependencies',
		'Updated mediawiki\/core', // git submodule autobumps
	);
	foreach ( $logoutput as $record ) {
		foreach( $skipLines as $skip ) {
			if ( preg_match( '/' . $skip . '/i', $record['subject'] ) ) {
				continue 2;
			}
		}

		$retval .= "* {{git|{$record['hash']}}} - <nowiki>";
		$retval .= $record['subject'] . '</nowiki>';
		if ( $record['bugs'] ) {
			$retval .= ' (';
			$retval .= implode( ", ", array_map( function( $b ) {
				if ( strpos( $b, 'T' ) !== false ) {
					return "{{phabricator|{$b}}}";
				} else {
					return "{{bugzilla|{$b}}}";
				}
			}, $record['bugs'] ) );
			$retval .= ')';
		}
		$retval .= "\n";
	}
	return $retval;
}

/**
 * @param string $oldbranch
 * @param string $newbranch
 * @param string $type
 * @param array $disabledExtension
 * @return string
 */
function get_all_submodule_change_markup( $oldbranch, $newbranch, $type, $disabledExtension = array() ) {
	$retval = '';
	$extrecords = get_submodule_versions( $oldbranch, $newbranch, $type );
	foreach ( $extrecords as $extrecord ) {
		if ( !isset( $extrecord['name'] ) || in_array( $extrecord['name'], $disabledExtension ) ) {
			continue;
		}
		if( !array_key_exists( 'oldrev', $extrecord ) ) {
			$printType = $type === 'extensions' ? 'extension' : 'skin';
			$retval .= get_change_log( $extrecord['name'], "* Newly deployed $printType\n" );
			continue;
		} elseif( !array_key_exists( 'newrev', $extrecord ) ) {
			$logoutput = useful_git_log( $extrecord['oldrev'], 'HEAD', $type, $extrecord['name'] );
		} else {
			$logoutput = useful_git_log( $extrecord['oldrev'], $extrecord['newrev'], $type, $extrecord['name'] );
		}
		$changes = filter_git_output( $logoutput );
		if( $changes != "" ) {
			$retval .= get_change_log( $extrecord['name'], $changes );
		}
	}
	return $retval;
}

/**
 * Gets a final change log entry
 *
 * @param string $name
 * @param string $changes
 * @return string
 */
function get_change_log( $name, $changes ) {
	return '=== ' . $name . " ===\n" . $changes;
}


/**
 * Main program flow
 * Get changes for core (git_cherry_log_output_core + filter_git_output)
 * Get extension markup (get_all_extension_change_markup)
 *   -> Get list of extensions (get_extension_versions)
 *   -> On each extension:
 *      ->  Get changes and filter (get_cherry_log_output_extension + filter_git_output)
 * @param array $argv
 */
function main( $argv ) {
	$disabledExtensions = array();
	if ( file_exists( __DIR__ . '/../make-wmf-branch/config.json' ) ) {
		$extensionLists = json_decode(
			file_get_contents( __DIR__ . '/../make-wmf-branch/config.json' ),
			true
		);
		if ( isset( $extensionLists['special_extensions'] ) ) {
			$disabledExtensions = array_keys( $extensionLists['special_extensions'] );
		}
	}

	list( $oldbranch, $newbranch ) = get_args( $argv );
	print "== Core changes ==\n";
	print filter_git_output( useful_git_log( $oldbranch, $newbranch ) );

	print "=== Vendor ===\n";
	$vendorVer = get_submodule_versions( $oldbranch, $newbranch, 'vendor' );
	if ( isset( $vendorVer[0] ) ) {
		$vendorVer = $vendorVer[0];
		print filter_git_output( useful_git_log( $vendorVer['oldrev'], $vendorVer['newrev'], null, 'vendor' ) );
	} else {
		print "No vendor changes\n";
	}

	print "== Extensions ==\n";
	print get_all_submodule_change_markup( $oldbranch, $newbranch, 'extensions', $disabledExtensions );

	print "== Skins ==\n";
	print get_all_submodule_change_markup( $oldbranch, $newbranch, 'skins' );
}

main( $argv );
