#!/bin/bash

set -eu -o pipefail

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 fully-qualified-image-name"
    exit 1
fi

fqin="$1"

source_dir=/srv/mediawiki-staging
default_base=webserver-image-base

### 

scriptdir="$(dirname "$0")"
supportdir="$scriptdir/../support"

###

base_image="$default_base"

last_build_id_file="$scriptdir/last-build"

if [ -f "$last_build_id_file" ]; then
    base_image="$(cat "$last_build_id_file")"
fi
if [ "${FORCE_FULL_BUILD:-false}" = "true" ]; then
    echo "FORCE_FULL_BUILD requested.   Using $default_base"
    base_image="$default_base"
fi

php_dir_to_keep="$(readlink "${source_dir}/php")"

time "$supportdir/build-image-incr.py" \
     "$default_base" "$source_dir" "/srv/mediawiki" "$fqin" \
     --layer "$base_image" \
     --exclude "**/.git" \
     --exclude /wmf-config \
     --exclude /tests \
     --exclude /src \
     --exclude /multiversion \
     --exclude /docroot/noc \
     --exclude /private \
     --include "/$php_dir_to_keep" \
     --exclude "/$php_dir_to_keep/cache" \
     --exclude "/$php_dir_to_keep/extensions" \
     --exclude "/$php_dir_to_keep/languages" \
     --exclude "/$php_dir_to_keep/skins" \
     --exclude "/$php_dir_to_keep/tests" \
     --exclude "/$php_dir_to_keep/vendor" \
     --exclude "/$php_dir_to_keep/**.php" \
     --exclude "/php-*"
