#!/bin/bash

set -eux -o pipefail

DEFAULT_GIT_BASE=https://gerrit.wikimedia.org/r

GIT_BASE=${GIT_BASE:-$DEFAULT_GIT_BASE}
MW_CONFIG_BRANCH=${MW_CONFIG_BRANCH:-master}

cat <<EOF
Stage /srv/mediawiki

CACHEBUSTER:      $CACHEBUSTER
GIT_BASE:         $GIT_BASE
MW_CONFIG_BRANCH: $MW_CONFIG_BRANCH
EOF

git clone --depth=1 --branch="${MW_CONFIG_BRANCH}" "${GIT_BASE}/operations/mediawiki-config" /srv/mediawiki
if [ "$GIT_BASE" != "$DEFAULT_GIT_BASE" ]; then
    git config --global "url.$GIT_BASE.insteadOf" "$DEFAULT_GIT_BASE"
fi
cd /srv/mediawiki
git submodule update --init --recursive
# hack: find the current latest branch from the php link
MW_BRANCH=$(readlink php | sed 's/^php-/wmf\//')
# Remove files that are not needed
rm -fr .git wmf-config tests php src multiversion docroot/noc
# Find broken links (typically to the php directory) and try to fix them.
# Do a temporary checkout of the branch. Note we don't use the "php" directory
# to avoid making broken links work by chance
git clone --depth=1 --branch="${MW_BRANCH}" "${GIT_BASE}/mediawiki/core" php
# Now remove from the php tree:
# - the languages directory
# - git
# - tests
# - all php source files, given we don't want them to be reachable
rm -rf php/languages php/tests php/.git
find /srv/mediawiki/php -name "*.php" -delete

