#!/bin/bash
MIGRATE_PATCH_DIR=`dirname "$(readlink -f "$0")"`
. $MIGRATE_PATCH_DIR/tc.sh
TMPFILE=`mktemp`

set -e
echo "${Blue}${Bold}----------------------------------${Rst}"
echo "Migrating patches for submodule $3"
echo "${Blue}${Bold}----------------------------------${Rst}"
cd $1/$3
git format-patch -k --stdout $4 > $TMPFILE
cd $2/$3
cat $TMPFILE | git am -3 -k
rm $TMPFILE
echo "${Blue}${Bold}----------------------------------${Rst}"
