#!/bin/bash

STAGE=/srv/mediawiki-staging
OLDVERSION=$1
TMPFILE=`mktemp`
MIGRATE_PATCH_DIR=`dirname "$(readlink -f "$0")"`
MIGRATE_FROM="$STAGE/php-$OLDVERSION"
MIGRATE_TO=`pwd`

. $MIGRATE_PATCH_DIR/tc.sh

set -e

if [ ! -d "$MIGRATE_FROM" ]; then
	echo 'USAGE: migrate-patch <VERSION>'
	echo
        echo 'Note: current working directory should be set to the root'
	echo '      of the new branch checkout'
	echo
	exit 1
fi

pushd $MIGRATE_FROM
echo "Migrating patches from $MIGRATE_FROM to $MIGRATE_TO"
git log --pretty=oneline @{u}..
git format-patch -k --stdout @{u}..> $TMPFILE
popd
cat $TMPFILE | git am -3 -k
rm $TMPFILE
cd $MIGRATE_FROM
echo "${Bold}${Blue}---------------------------${Rst}"
echo "${Bold}Migrating submodule patches${Rst}"
git submodule summary
echo "${Bold}${Blue}---------------------------${Rst}"
git submodule summary | grep '\*.*' | cut -d ' ' -f 2-3 | xargs -L 1 $MIGRATE_PATCH_DIR/migrate-submodule-patch $MIGRATE_FROM $MIGRATE_TO
