#!/usr/bin/env python3

import json
import subprocess
import sys

import findtrain


TWO_WEEKS = subprocess.check_output(
    ['date', '-I', '--date', 'Monday+14days']).decode('utf8')
MONDAY = findtrain.get_next_monday(findtrain.parse_date(TWO_WEEKS))

TF = findtrain.find_train_finder(MONDAY)

if __name__ == '__main__':
    if TF.is_declined:
        sys.exit(1)

    print(json.dumps(TF.next.task))
