#!/usr/bin/env python3
"""
Tell me....is there a train in two weeks?
"""

import json
import subprocess
import sys

from context import deploymentcalendar


TWO_WEEKS = subprocess.check_output(
    ['date', '-I', '--date', 'Monday+7days']).decode('utf8').strip()
MONDAY = deploymentcalendar.findtrain.get_next_monday(
    deploymentcalendar.findtrain.parse_date(TWO_WEEKS)
)

TF = deploymentcalendar.findtrain.find_train_finder(MONDAY)

if __name__ == '__main__':
    if TF.is_declined:
        print('No train week of {}'.format(TWO_WEEKS))
        sys.exit(1)

    next_week = TF.next.task
    next_week['date'] = TWO_WEEKS

    print(json.dumps(next_week))
